<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NetworkWidget</AssemblyName>
    <RootNamespace>NetworkWidget</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.2.9</Version>
    <Company>Jordan</Company>
    <Product>Network Widget</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManagedNativeWifi" Version="3.0.2" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
