using System.Collections.Generic;

namespace Anemo.Core
{
    // Common TCP services, per IANA's service name registry - not exhaustive, just the
    // ports someone scanning their own network would actually recognize.
    public static class WellKnownPorts
    {
        private static readonly Dictionary<int, string> Names = new()
        {
            [20] = "FTP-DATA",
            [21] = "FTP",
            [22] = "SSH",
            [23] = "Telnet",
            [25] = "SMTP",
            [53] = "DNS",
            [67] = "DHCP",
            [69] = "TFTP",
            [80] = "HTTP",
            [88] = "Kerberos",
            [110] = "POP3",
            [111] = "RPCbind",
            [123] = "NTP",
            [135] = "MS-RPC",
            [137] = "NetBIOS-NS",
            [138] = "NetBIOS-DGM",
            [139] = "NetBIOS-SSN",
            [143] = "IMAP",
            [161] = "SNMP",
            [179] = "BGP",
            [389] = "LDAP",
            [443] = "HTTPS",
            [445] = "SMB",
            [465] = "SMTPS",
            [514] = "Syslog",
            [515] = "LPD",
            [548] = "AFP",
            [554] = "RTSP",
            [587] = "SMTP (Submission)",
            [631] = "IPP",
            [636] = "LDAPS",
            [873] = "rsync",
            [989] = "FTPS-DATA",
            [990] = "FTPS",
            [993] = "IMAPS",
            [995] = "POP3S",
            [1080] = "SOCKS",
            [1194] = "OpenVPN",
            [1433] = "MSSQL",
            [1521] = "Oracle DB",
            [1723] = "PPTP",
            [1883] = "MQTT",
            [2049] = "NFS",
            [2082] = "cPanel",
            [2083] = "cPanel (SSL)",
            [2222] = "SSH (alt)",
            [2375] = "Docker",
            [2376] = "Docker (TLS)",
            [3000] = "Dev Server",
            [3128] = "Squid Proxy",
            [3306] = "MySQL",
            [3389] = "RDP",
            [3690] = "Subversion",
            [4443] = "HTTPS (alt)",
            [5000] = "UPnP / Dev Server",
            [5060] = "SIP",
            [5222] = "XMPP",
            [5353] = "mDNS",
            [5357] = "WSDAPI",
            [5432] = "PostgreSQL",
            [5601] = "Kibana",
            [5900] = "VNC",
            [5985] = "WinRM",
            [5986] = "WinRM (HTTPS)",
            [6379] = "Redis",
            [6443] = "Kubernetes API",
            [6881] = "BitTorrent",
            [7000] = "AirPlay",
            [8000] = "HTTP (alt)",
            [8008] = "HTTP (alt)",
            [8080] = "HTTP Proxy",
            [8081] = "HTTP (alt)",
            [8083] = "InfluxDB",
            [8086] = "InfluxDB API",
            [8443] = "HTTPS (alt)",
            [8888] = "HTTP (alt)",
            [9000] = "PHP-FPM / Dev",
            [9090] = "Prometheus",
            [9092] = "Kafka",
            [9200] = "Elasticsearch",
            [9418] = "Git",
            [10000] = "Webmin",
            [11211] = "Memcached",
            [27017] = "MongoDB",
            [32400] = "Plex",
        };

        public static string GetServiceName(int port) => Names.GetValueOrDefault(port, "-");
    }
}
