<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Anemo.Scanner</AssemblyName>
    <RootNamespace>Anemo.Scanner</RootNamespace>
    <ApplicationIcon>..\app.ico</ApplicationIcon>
    <Version>1.3.0</Version>
    <Company>Jordan</Company>
    <Product>Anemo Scanner</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Anemo.Core\Anemo.Core.csproj" />
  </ItemGroup>

</Project>
